package com.example.digitalhousefoods

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.core.content.ContextCompat
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.digitalhousefoods.domain.Food
import com.example.digitalhousefoods.domain.Restaurant
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {

    var listaRestaurant = getAllRestaurant()
    var adapter = RestaurantAdapter(listaRestaurant)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        setSupportActionBar(findViewById(R.id.toolbar))

        val actionBar = supportActionBar
        actionBar!!.title = "Digital House Foods"

        window.setStatusBarColor(ContextCompat.getColor(this, R.color.purple_700))

        rvRestaurant.adapter = adapter
        rvRestaurant.layoutManager = LinearLayoutManager(this)
        rvRestaurant.setHasFixedSize(false)
    }

    private fun getAllRestaurant(): ArrayList<Restaurant> {
        return arrayListOf(
            Restaurant(
                R.drawable.image1,
                "Tony Roma's",
                "Av. Lavandisca 717 - Indianópolis, São Paulo",
                "Fecha às 22:00",
                arrayListOf(
                    Food(R.drawable.image4, "describe1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe4", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe5", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe6", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                )
            ),
            Restaurant(
                R.drawable.image4,
                "Aoyama - Moema",
                "Alameda dos Arapanés, 532 - Moema",
                "Fecha às 00:00",
                arrayListOf(
                    Food(R.drawable.image4, "describe7", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe8", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe9", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe10", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe11", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe12", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                ),
            ),
            Restaurant(
                R.drawable.image5,
                "Outback - Moema",
                "Av. Moaci, 187, 187 - Moema, São Paulo",
                "Fecha às 00:00",
                arrayListOf(
                    Food(R.drawable.image4, "describe13", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe14", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe15", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe16", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe17", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe18", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                )
            ),
            Restaurant(
                R.drawable.image3,
                "Sí Señor",
                "Alameda Jauaperi, 626 - Moema",
                "Fecha às 01:00",
                arrayListOf(
                    Food(R.drawable.image4, "describe19", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe20", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe21", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe22", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe23", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                    Food(R.drawable.image4, "describe24", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia ex ut rhoncus venenatis. Aliquam erat volutpat. Quisque eu mattis ante, nec malesuada quam. Fusce in metus quis risus congue mattis vulputate in nisl. Suspendisse nunc dui, pellentesque vitae nunc vel, sodales porttitor quam. Vestibulum nisi quam, fermentum id metus sed, consequat aliquam orci. Pellentesque consequat consectetur ipsum non imperdiet. Nam consequat nunc lobortis congue commodo. Ut sed fringilla mauris. Aliquam tristique nibh id nisl lobortis, at auctor arcu ultricies. Cras ornare rhoncus est sed rutrum. Integer viverra nulla efficitur, varius nulla quis, porttitor justo. Quisque leo sapien, suscipit sit amet cursus varius, vestibulum id tellus. Aliquam vitae condimentum lorem."),
                )
            ),
        )
    }
}